name: Store and Display Latest Merged PR Description

on:
  push:
    branches:
      - develop

jobs:
  store-and-display-latest-merged-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest merged pull request description
        id: fetch-pr
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pulls } = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              base: 'main',
              sort: 'updated',
              direction: 'desc',
              per_page: 100
            });

            const latestMergedPR = pulls.find(pr => pr.merged_at && pr.base.ref === 'main');
            if (latestMergedPR) {
              return { pr_description: latestMergedPR.body };
            } else {
              return { pr_description: 'No merged pull requests found into main.' };
            }

      - name: Set PR description as environment variable
        run: echo "PR_DESCRIPTION=${{ steps.fetch-pr.outputs.pr_description }}" >> $GITHUB_ENV

      - name: Display PR description
        run: echo $PR_DESCRIPTION