name: Display All Merged PR Descriptions

on:
  push:
    branches:
      - main

jobs:
  display-all-merged-pr-descriptions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all merged pull request descriptions
        id: fetch-prs
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              sort: 'updated',
              direction: 'desc',
              per_page: 100
            });

            const mergedPRs = pulls.filter(pr => pr.merged_at && pr.base.ref === 'main');
            if (mergedPRs.length > 0) {
              mergedPRs.forEach(pr => {
                console.log(`PR #${pr.number}: ${pr.title}`);
                console.log(`Description: ${pr.body}`);
              });
              return { pr_descriptions: mergedPRs.map(pr => pr.body).join('\n\n') };
            } else {
              console.log('No merged pull requests found into main.');
              return { pr_descriptions: 'No merged pull requests found into main.' };
            }

      - name: Set PR descriptions as environment variable
        run: echo "PR_DESCRIPTIONS=${{ steps.fetch-prs.outputs.pr_descriptions }}" >> $GITHUB_ENV

      - name: Display PR descriptions
        run: echo "The descriptions of all merged PRs are: $PR_DESCRIPTIONS"