name: Store PR Description on Merge or Manual Trigger

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  list-prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: sudo apt-get install gh

    - name: Fetch and Display Latest Merged PR Description
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Fetch the latest merged pull request into main
        latest_pr=$(gh pr list --state merged --base main --sort updated --json number,title,body --jq '.')
        
        # Extract the description of the latest merged pull request
        pr_number=$(echo "$latest_pr" | jq -r '.number')
        pr_title=$(echo "$latest_pr" | jq -r '.title')
        pr_description=$(echo "$latest_pr" | jq -r '.body')
        
        # Output the description of the latest merged pull request
        echo "Latest Merged Pull Request: #$pr_number - $pr_title"
        echo "Description: $pr_description"